apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "gc-argo-api"
  annotations:
    github.com/project-slug: qwiklabs-gcp-03-07dc91f1c261/gc-argo-api
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: group:platform
  lifecycle: experimental
